package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1



/**
 * BancaLocalId generated by hbm2java
 */
public class BancaLocalId  implements java.io.Serializable {


     private int idLocal;
     private int idBanca;

    public BancaLocalId() {
    }

    public BancaLocalId(int idLocal, int idBanca) {
       this.idLocal = idLocal;
       this.idBanca = idBanca;
    }
   
    public int getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(int idLocal) {
        this.idLocal = idLocal;
    }
    public int getIdBanca() {
        return this.idBanca;
    }
    
    public void setIdBanca(int idBanca) {
        this.idBanca = idBanca;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BancaLocalId) ) return false;
		 BancaLocalId castOther = ( BancaLocalId ) other; 
         
		 return (this.getIdLocal()==castOther.getIdLocal())
 && (this.getIdBanca()==castOther.getIdBanca());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdLocal();
         result = 37 * result + this.getIdBanca();
         return result;
   }   


}


