package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BancaLocal generated by hbm2java
 */
public class BancaLocal  implements java.io.Serializable {


     private BancaLocalId id;
     private Banca banca;
     private Localizacao localizacao;
     private Date dataInstalacao;
     private Date dataRemocao;

    public BancaLocal() {
    }

	
    public BancaLocal(BancaLocalId id, Banca banca, Localizacao localizacao) {
        this.id = id;
        this.banca = banca;
        this.localizacao = localizacao;
    }
    public BancaLocal(BancaLocalId id, Banca banca, Localizacao localizacao, Date dataInstalacao, Date dataRemocao) {
       this.id = id;
       this.banca = banca;
       this.localizacao = localizacao;
       this.dataInstalacao = dataInstalacao;
       this.dataRemocao = dataRemocao;
    }
   
    public BancaLocalId getId() {
        return this.id;
    }
    
    public void setId(BancaLocalId id) {
        this.id = id;
    }
    public Banca getBanca() {
        return this.banca;
    }
    
    public void setBanca(Banca banca) {
        this.banca = banca;
    }
    public Localizacao getLocalizacao() {
        return this.localizacao;
    }
    
    public void setLocalizacao(Localizacao localizacao) {
        this.localizacao = localizacao;
    }
    public Date getDataInstalacao() {
        return this.dataInstalacao;
    }
    
    public void setDataInstalacao(Date dataInstalacao) {
        this.dataInstalacao = dataInstalacao;
    }
    public Date getDataRemocao() {
        return this.dataRemocao;
    }
    
    public void setDataRemocao(Date dataRemocao) {
        this.dataRemocao = dataRemocao;
    }




}


