package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1


import exceptions.ValidacaoException;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer idCategoria;
     private String descricao;
     private Set livros = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String descricao) {
        this.descricao = descricao;
    }
    public Categoria(String descricao, Set livros) {
       this.descricao = descricao;
       this.livros = livros;
    }
   
    public Integer getIdCategoria() {
        return this.idCategoria;
    }
    
    public void setIdCategoria(Integer idCategoria) {
        this.idCategoria = idCategoria;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getLivros() {
        return this.livros;
    }
    
    public void setLivros(Set livros) {
        this.livros = livros;
    }
    @Override
    public String toString() {
        return descricao;
    }

    public void validar() throws ValidacaoException {
        if (descricao == null || descricao.equals("")) {

            throw new ValidacaoException("Campo nome não Preenchido");
        }
    }


}


