package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1

import exceptions.ValidacaoException;
import java.util.HashSet;
import java.util.Set;

/**
 * Editora generated by hbm2java
 */
public class Editora implements java.io.Serializable {

    private Integer idEditora;
    private String nome;
    private Set livros = new HashSet(0);

    public Editora() {
    }

    public Editora(String nome) {
        this.nome = nome;
    }

    public Editora(String nome, Set livros) {
        this.nome = nome;
        this.livros = livros;
    }

    public Editora(Integer idEditora, String nome) {
        this.idEditora = idEditora;
        this.nome = nome;
    }

    public Integer getIdEditora() {
        return this.idEditora;
    }

    public void setIdEditora(Integer idEditora) {
        this.idEditora = idEditora;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Set getLivros() {
        return this.livros;
    }

    public void setLivros(Set livros) {
        this.livros = livros;
    }

    @Override
    public String toString() {
        return getNome();
    }

    public void validar() throws ValidacaoException {
        if (nome == null || nome.equals("")) {

            throw new ValidacaoException("Campo nome não Preenchido");
        }
    }

}
