package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Emprestimo generated by hbm2java
 */
public class Emprestimo  implements java.io.Serializable {


     private Integer idEmprestimo;
     private Banca banca;
     private Exemplar exemplar;
     private Date dataEmprestimo;
     private Date dataDevolucao;

    public Emprestimo() {
    }

	
    public Emprestimo(Banca banca, Exemplar exemplar) {
        this.banca = banca;
        this.exemplar = exemplar;
    }
    public Emprestimo(Banca banca, Exemplar exemplar, Date dataEmprestimo, Date dataDevolucao) {
       this.banca = banca;
       this.exemplar = exemplar;
       this.dataEmprestimo = dataEmprestimo;
       this.dataDevolucao = dataDevolucao;
    }
   
    public Integer getIdEmprestimo() {
        return this.idEmprestimo;
    }
    
    public void setIdEmprestimo(Integer idEmprestimo) {
        this.idEmprestimo = idEmprestimo;
    }
    public Banca getBanca() {
        return this.banca;
    }
    
    public void setBanca(Banca banca) {
        this.banca = banca;
    }
    public Exemplar getExemplar() {
        return this.exemplar;
    }
    
    public void setExemplar(Exemplar exemplar) {
        this.exemplar = exemplar;
    }
    public Date getDataEmprestimo() {
        return this.dataEmprestimo;
    }
    
    public void setDataEmprestimo(Date dataEmprestimo) {
        this.dataEmprestimo = dataEmprestimo;
    }
    public Date getDataDevolucao() {
        return this.dataDevolucao;
    }
    
    public void setDataDevolucao(Date dataDevolucao) {
        this.dataDevolucao = dataDevolucao;
    }




}


