package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exemplar generated by hbm2java
 */
public class Exemplar  implements java.io.Serializable {


     private Integer idExemplar;
     private Banca banca;
     private Livro livro;
     private Boolean estado;
     private Integer ntombo;
     private Set emprestimos = new HashSet(0);

    public Exemplar() {
    }

	
    public Exemplar(Banca banca, Livro livro) {
        this.banca = banca;
        this.livro = livro;
    }
    public Exemplar(Banca banca, Livro livro, Boolean estado, Integer ntombo, Set emprestimos) {
       this.banca = banca;
       this.livro = livro;
       this.estado = estado;
       this.ntombo = ntombo;
       this.emprestimos = emprestimos;
    }
   
    public Integer getIdExemplar() {
        return this.idExemplar;
    }
    
    public void setIdExemplar(Integer idExemplar) {
        this.idExemplar = idExemplar;
    }
    public Banca getBanca() {
        return this.banca;
    }
    
    public void setBanca(Banca banca) {
        this.banca = banca;
    }
    public Livro getLivro() {
        return this.livro;
    }
    
    public void setLivro(Livro livro) {
        this.livro = livro;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Integer getNtombo() {
        return this.ntombo;
    }
    
    public void setNtombo(Integer ntombo) {
        this.ntombo = ntombo;
    }
    public Set getEmprestimos() {
        return this.emprestimos;
    }
    
    public void setEmprestimos(Set emprestimos) {
        this.emprestimos = emprestimos;
    }




}


