package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1

import exceptions.ValidacaoException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Livro generated by hbm2java
 */
public class Livro implements java.io.Serializable {

    private Integer idLivro;
    private Editora editora;
    private String titulo;
    private String isbn;
    private String cdBarras;
    private Set exemplars = new HashSet(0);
    private Set autors = new HashSet(0);
    private Set categorias = new HashSet(0);

    public Livro() {
    }

    public Livro(Editora editora, String titulo, String isbn) {
        this.editora = editora;
        this.titulo = titulo;
        this.isbn = isbn;
    }

    public Livro(Editora editora, String titulo, String isbn, String cdBarras, List<Autor> autores, List<Categoria> categorias) {
        this.editora = editora;
        this.titulo = titulo;
        this.isbn = isbn;
        this.cdBarras = cdBarras;
        this.autors.addAll(autores);
        this.categorias.addAll(categorias);
    }

    public Integer getIdLivro() {
        return this.idLivro;
    }

    public void setIdLivro(Integer idLivro) {
        this.idLivro = idLivro;
    }

    public Editora getEditora() {
        return this.editora;
    }

    public void setEditora(Editora editora) {
        this.editora = editora;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    public String getCdBarras() {
        return this.cdBarras;
    }

    public void setCdBarras(String cdBarras) {
        this.cdBarras = cdBarras;
    }

    public Set getExemplars() {
        return this.exemplars;
    }

    public void setExemplars(Set exemplars) {
        this.exemplars = exemplars;
    }

    public void addExemplars(List<Exemplar> exemplares) {
        this.exemplars.addAll(exemplares);
    }

    public Set getAutors() {
        return this.autors;
    }

    public void setAutors(Set autors) {
        this.autors = autors;
    }

    public void addAutors(List<Autor> autores) {
        this.autors.addAll(autores);
    }

    public Set getCategorias() {
        return this.categorias;
    }

    public void setCategorias(Set categorias) {
        this.categorias.addAll(categorias);
    }

    public void addCategorias(List<Categoria> categorias) {
        this.categorias.addAll( categorias);
    }

    @Override
    public String toString() {
        return titulo;
    }

    public void validar() throws ValidacaoException {
        if ((titulo == null || titulo.equals(""))
                || editora == null
                || (isbn == null || isbn.equals(""))) {

            throw new ValidacaoException("Campo nome não Preenchido");
        }
    }

}
