package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Localizacao generated by hbm2java
 */
public class Localizacao  implements java.io.Serializable {


     private Integer idLocal;
     private Responsavel responsavel;
     private String descricao;
     private String rua;
     private String bairro;
     private String cidade;
     private Integer numero;
     private String estado;
     private Set bancaLocals = new HashSet(0);

    public Localizacao() {
    }

	
    public Localizacao(Responsavel responsavel, String descricao) {
        this.responsavel = responsavel;
        this.descricao = descricao;
    }
    public Localizacao(Responsavel responsavel, String descricao, String rua, String bairro, String cidade, Integer numero, String estado, Set bancaLocals) {
       this.responsavel = responsavel;
       this.descricao = descricao;
       this.rua = rua;
       this.bairro = bairro;
       this.cidade = cidade;
       this.numero = numero;
       this.estado = estado;
       this.bancaLocals = bancaLocals;
    }
   
    public Integer getIdLocal() {
        return this.idLocal;
    }
    
    public void setIdLocal(Integer idLocal) {
        this.idLocal = idLocal;
    }
    public Responsavel getResponsavel() {
        return this.responsavel;
    }
    
    public void setResponsavel(Responsavel responsavel) {
        this.responsavel = responsavel;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getBancaLocals() {
        return this.bancaLocals;
    }
    
    public void setBancaLocals(Set bancaLocals) {
        this.bancaLocals = bancaLocals;
    }




}


