package model.entidades;
// Generated 14/06/2019 15:29:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Responsavel generated by hbm2java
 */
public class Responsavel  implements java.io.Serializable {


     private Integer idResponsavel;
     private String nome;
     private String telefone;
     private Set localizacaos = new HashSet(0);

    public Responsavel() {
    }

    public Responsavel(String nome, String telefone, Set localizacaos) {
       this.nome = nome;
       this.telefone = telefone;
       this.localizacaos = localizacaos;
    }
   
    public Integer getIdResponsavel() {
        return this.idResponsavel;
    }
    
    public void setIdResponsavel(Integer idResponsavel) {
        this.idResponsavel = idResponsavel;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Set getLocalizacaos() {
        return this.localizacaos;
    }
    
    public void setLocalizacaos(Set localizacaos) {
        this.localizacaos = localizacaos;
    }




}


